name: poster_pro
description: "Poster Pro - ناشر برو. تطبيق نشر تلقائي على مجموعات فيسبوك."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/splash-icon.png
    - assets/images/favicon.png
